return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "black",
      "beautysh",
      "clang-format",
      "clangd",
      "codelldb",
      "debugpy",
      "djlint",
      "eslint-lsp",
      "isort",
      "js-debug-adapter",
      "latexindent",
      "lua-language-server",
      "mypy",
      "prettier",
      "pyright",
      "ruff",
      "stylua",
      "sql-formatter",
      "typescript-language-server",
    },
  },
}
